name: Generate idx highlights content for idx

on:
  schedule:
    - cron: '0 5 * * 6' # Run every saturday at 11am/12pm (Western Indonesia Time)
  
  workflow_dispatch:
      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10' # Replace with your desired Python version

    - name: Install Poppler
        run: sudo apt-get install -y poppler-utils

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run test.py
      env:
        user: ${{ secrets.USER }}
        host: ${{ secrets.HOST }}
        password: ${{secrets.PASSWORD}}
        port: ${{secrets.port}}
        dbname: ${{secrets.dbname}}
      run: python main.py

    - name: commit files
      run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff-index --quiet HEAD || (git commit -a -m "updated logs" --allow-empty)
          
    - name: push changes
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${{ secrets.TOKEN_GITHUB }}
        branch: main 
