name: Sync json_output to repo_b

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour
  workflow_dispatch:

jobs:
  sync-json-output:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo_a
        uses: actions/checkout@v4
    
      - name: Setup Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
      
      - name: Shallow clone repo_b
        run: |
          git clone --depth 1 https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/geraldbryan/github_action_tutorial.git
          cp -r json_output/* repo_b/json_output/
          cd repo_b
          git add json_output
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Update json_output from repo_a"
            git push
          fi
