name: Sync json_output to repo_b

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour
  workflow_dispatch:

jobs:
  sync-json-output:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo_a
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup Git
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'

      - name: Clone repo_b
        run: |
          git clone https://${{ secrets.REPO_B_PUSH_TOKEN }}@github.com/geraldbryan/github_action_tutorial.git
          cd repo_b
          mkdir -p json_output
          rm -rf json_output/*
          cp -r ../json_output/* json_output/
          
          git add json_output
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Update json_output from repo_a"
            git push
          fi
    env:
      GITHUB_TOKEN: ${{ secrets.REPO_B_PUSH_TOKEN }}
